apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
 name: basic
spec:
 providerConfigRef:
  name: awsprvcfg
 providerRef:
  name: crossplane-provider-aws
 forProvider:
  dbInstanceClass: db.t2.small
  engine: postgre
