apiVersion: ec2.aws.crossplane.io/v1beta1 
kind: VPC
metadata:
  name: idly
spec:
  forProvider:  
    region: us-east-1
    cidrBlock: 10.2.2.2/24
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    tags:
      - key: Name
        value: idly
  providerRef:
    name: crossplane-provider-aws
  providerConfigRef:
    name: awspswd
