apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: example-dbinstancehub
spec:
  forProvider:
    region: us-east-1
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    autogeneratePassword: true
    backupRetentionPeriod: 14
    dbInstanceClass: db.t2.micro
    dbName: example
    engine: postgres
    engineVersion: "12.9"
    masterUsername: adminuser
    masterUserPasswordSecretRef:
      key: password
      name: example-dbinstance-sec
      namespace: crossplane-system
    preferredBackupWindow: "7:00-8:00"
    preferredMaintenanceWindow: "Sat:8:00-Sat:11:00"
    publiclyAccessible: false
    skipFinalSnapshot: true
    storageEncrypted: false
    storageType: gp2
    dbParameterGroupName: example-dbparametergroup
    applyImmediately: true
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: crossplane-system
  providerConfigRef:
    name: awsprvcfg
