apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rds
spec:
  forProvider:
    region: us-east-1
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t3.small
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: postgres
    engineVersion: "12.9"
    finalDBSnapshotIdentifier: muvaf-test
    licenseModel: general-public-license
    masterUsername: admin
    multiAZ: true
    port: 5432
    publiclyAccessible: false
    storageEncrypted: false
    storageType: gp2
  providerRef:
    name: crossplane-provider-aws
  providerConfigRef:
    name: awsprvcfg
  writeConnectionSecretToRef:
    name: 66258c8a-24ad-45e6-a79e-1d54c19d908c-mysqlserver
    namespace: crossplane-system
