--- 
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: testyrds
spec: 
  forProvider: 
    dbInstanceClass: db.t2.small
    engine: postgres
    engineVersion: "12"
    masterUsername: masteruser
    publiclyAccessible: true
    region: us-east-1
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef: 
    namespace: crossplane-system
    name: rds-sec
  providerConfigRef:
    name: default
  providerRef:
    name: crossplane-provider-aws
