apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rdsred
spec:
  forProvider:
    region: us-east-1
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t3.small
    deletionProtection: false
    enableIAMDatabaseAuthentication: true
    enablePerformanceInsights: false
    engine: postgres
    engineVersion: "12"
    #finalDBSnapshotIdentifier: muvaf-test
    skipFinalSnapshotBeforeDeletion: true
    monitoringRoleArn: arn:aws:iam::745359908730:role/rds-monitoring-role
    #licenseModel: general-public-license
    masterUsername: pgboi
    monitoringInterval: 5
    multiAZ: true
    port: 5432
    publiclyAccessible: true
    storageEncrypted: false
    storageType: gp2
  providerConfigRef:
    name: awsprvcfg
    #writeConnectionSecretToRef:
    #name: 66258c8a-24ad-45e6-a79e-1d54c19d908c-mysqlserver
    #namespace: crossplane-system
