apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: sample-subnet-group
spec:
  forProvider:
    region: us-east-1
    description: "sample group"
    subnetIdRefs:
     - name: sample-subnet2
     - name: subnet-f
    subnetIds: 
     - subnet-a
     - subnet-d
     - subnet-c
  providerConfigRef:
    name: awsprvcfg
  providerRef:
    name: crossplane-provider-aws
