apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: sample-subnet2
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 1.0.1.0/24
    vpcId: vpc-id
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: awsprvcfg
  providerRef:
    name: crossplane-provider-aws
