apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata: 
  name: gcpprvcfg
spec: 
  credentials: 
    secretRef: 
      key: creds
      name: gcp-creds
      namespace: crossplane-system
    source: Secret
  projectID: "mojorojo"
